from lib.JsonHandler import JsonHandler
import tornado.web
from tornado.concurrent import Future
from tornado import gen
import random

class SplitHandler(JsonHandler):
    def initialize(self):
        self.gameDict = SplitHandler.getGameDict()
        self.keys = SplitHandler.getOrderedKeys()
        self.seed = 6294
        self.offset = 0
        random.Random(self.seed).shuffle(self.keys)

    @gen.coroutine
    def get(self):
        # Parse the random setup
        offset = int(self.get_argument("offset", self.offset, True))
        
        # Get the next entry
        ndx = offset % len(self.keys)
        next = (ndx + 1) % len(self.keys)
        prev = (ndx - 1) % len(self.keys)
        key = self.keys[ndx]
        entry = self.gameDict[key]

        # Yield for async triage purposes
        entryFuture = Future()
        entryFuture.set_result((prev, next, {"key": key, key: entry}))
        result = yield entryFuture
        
        # Return the de facto result
        self.response = {"prev": result[0], "next": result[1], "entry": result[2]}
        self.write_json()
        
    def getOrderedKeys():
        return ['aura','alas','aria','adit','alms','ares','anus','aged','arse','bear','bend','best','bean','bone','buff','boot','boon','boat','buoy','bass','boom','bell','bang','beef','bash','bale','bait','bead','bing','barn','cost','card','core','cant','coat','cute','cord','cafe','coin','clue','cane','cone','cuff','coal','deal','door','dash','deed','dour','duly','dent','dole','dirt','dote','dial','duel','ding','does','doge','ever','else','ears','fire','fish','feel','feed','file','foot','foil','fray','fuel','feat','feet','font','fist','fest','fend','foal','gait','grin','gale','gang','gash','guts','gaga','hang','hole','host','hard','heed','hero','hood','holy','hoot','hose','heal','held','jeer','july','keel','lend','last','long','lily','lure','lost','lion','lust','lash','lent','leen','loon','liar','lung','lies','mean','move','moon','mole','main','most','mute','meal','mite','mane','mile','mule','mace','male','nest','near','neon','nine','nile','noon','oral','oxen','pale','pace','pole','prey','push','poet','pity','pile','pier','pray','peon','pate','pant','read','room','ring','rule','reel','real','rain','rage','role','rein','rote','rely','reef','riff','rile','rung','suit','show','spot','spin','sage','spit','sure','send','sale','shun','scam','that','this','tide','toil','tent','tale','tang','uses','vein','vice','vile','vial','wary','wing','wily','wiry','accent','banter','create','corral','caring','cheers','cellar','decent','derive','defend','equity','estate','edible','facile','garner','homage','innate','intact','insure','indent','jumble','living','laying','metric','marble','notion','outing','recess','relate','resent','spring','subtle','string','stable','though','toward','tenent','unsung','unsure','verity','vanish','wading','waters']
                
    def getGameDict():
        return  {
                    'aura': ['aurora'],
                    'alas': ['alohas', 'alphas'],
                    'aria': ['arabia'],
                    'adit': ['adroit'],
                    'alms': ['alarms', 'albums'],
                    'ares': ['arches', 'armies', 'arises', 'argues'],
                    'anus': ['animus'],
                    'aged': ['agreed', 'agazed'],
                    'arse': ['arouse', 'araise', 'arrose', 'ariose'],
                    'bear': ['beggar'],
                    'bend': ['beyond', 'behind'],
                    'best': ['behest'],
                    'bean': ['bemoan', 'bedpan', 'bemean'],
                    'bone': ['bovine'],
                    'buff': ['buyoff'],
                    'boot': ['bonmot', 'boycot'],
                    'boon': ['boston', 'bonbon'],
                    'boat': ['bobcat'],
                    'buoy': ['busboy'],
                    'bass': ['badass'],
                    'boom': ['bottom'],
                    'bell': ['befall', 'befell'],
                    'bang': ['baring', 'baking', 'baying'],
                    'beef': ['belief'],
                    'bash': ['banish'],
                    'bale': ['baffle', 'battle', 'babble', 'bangle'],
                    'bait': ['bandit'],
                    'bead': ['behead'],
                    'bing': ['biting', 'biding', 'biking'],
                    'barn': ['bayern'],
                    'cost': ['cohost', 'coyest', 'copist'],
                    'card': ['canard'],
                    'core': ['cohere'],
                    'cant': ['cadent'],
                    'coat': ['combat', 'comsat'],
                    'cute': ['curate'],
                    'cord': ['coward'],
                    'cafe': ['carafe'],
                    'coin': ['cousin', 'coffin'],
                    'clue': ['clique'],
                    'cane': ['canine', 'capone'],
                    'cone': ['cosine'],
                    'cuff': ['cutoff'],
                    'coal': ['corral', 'costal'],
                    'deal': ['denial', 'dental', 'dermal'],
                    'door': ['doctor'],
                    'dash': ['danish'],
                    'deed': ['deemed', 'denied', 'defied', 'decked', 'dented', 'demoed', 'deuced', 'delved', 'debted'],
                    'dour': ['dolour'],
                    'duly': ['dually', 'dumbly'],
                    'dent': ['decent', 'decant'],
                    'dole': ['double', 'docile', 'doodle', 'dongle', 'doable'],
                    'dirt': ['divert'],
                    'dote': ['donate'],
                    'dial': ['dismal'],
                    'duel': ['duffel'],
                    'ding': ['dining', 'diving', 'dicing'],
                    'does': ['douses', 'dodges', 'dogies'],
                    'doge': ['dosage'],
                    'ever': ['evader', 'evoker'],
                    'else': ['elapse', 'elipse'],
                    'ears': ['eaters', 'eagers', 'easers'],
                    'fire': ['figure'],
                    'fish': ['finish'],
                    'feel': ['fennel'],
                    'feed': ['felled', 'feared', 'fenced', 'felted', 'fended', 'feuded'],
                    'file': ['fickle', 'fiddle', 'finale', 'fizzle'],
                    'foot': ['forgot'],
                    'foil': ['fossil'],
                    'fray': ['friday'],
                    'fuel': ['funnel'],
                    'feat': ['fermat'],
                    'feet': ['ferret'],
                    'font': ['foment'],
                    'fist': ['finest'],
                    'fest': ['fewest'],
                    'fend': ['fecund'],
                    'foal': ['formal'],
                    'gait': ['gambit'],
                    'grin': ['gratin', 'gradin'],
                    'gale': ['gaggle', 'gamble', 'gargle', 'garble'],
                    'gang': ['gaming', 'gaping', 'gazing', 'gating'],
                    'gash': ['garish'],
                    'guts': ['guests', 'guilts'],
                    'gaga': ['galaga'],
                    'hang': ['hazing', 'having', 'hating'],
                    'hole': ['hobble'],
                    'host': ['honest'],
                    'hard': ['hazard'],
                    'heed': ['headed', 'heaved', 'heated', 'heeded', 'hemmed', 'helped', 'healed', 'heaped', 'hefted', 'hedged', 'herded', 'helmed'],
                    'hero': ['hetero'],
                    'hood': ['hotrod'],
                    'holy': ['homily', 'homely', 'hourly'],
                    'hoot': ['hotpot'],
                    'hose': ['hoarse'],
                    'heal': ['herbal'],
                    'held': ['herald', 'herold'],
                    'jeer': ['jester'],
                    'july': ['justly'],
                    'keel': ['kernel', 'kennel', 'kerbel'],
                    'lend': ['legend'],
                    'last': ['latest', 'lamest', 'laxest'],
                    'long': ['loving', 'losing'],
                    'lily': ['likely', 'lively'],
                    'lure': ['lustre'],
                    'lost': ['locust', 'lowest'],
                    'lion': ['liason'],
                    'lust': ['lutist'],
                    'lash': ['lavish'],
                    'lent': ['levant', 'learnt'],
                    'leen': ['leaven', 'lessen'],
                    'loon': ['london', 'lotion'],
                    'liar': ['linear'],
                    'lung': ['luring', 'lubing'],
                    'lies': ['lilies', 'lieges', 'litres', 'livres'],
                    'mean': ['median', 'merman'],
                    'move': ['motive', 'mojave', 'mohave'],
                    'moon': ['motion', 'mormon'],
                    'mole': ['mobile', 'module', 'morale', 'mottle'],
                    'main': ['margin', 'marlin'],
                    'most': ['modest'],
                    'mute': ['mutate'],
                    'meal': ['menial', 'mental', 'medial'],
                    'mite': ['minute'],
                    'mane': ['marine'],
                    'mile': ['mingle', 'middle', 'mistle'],
                    'mule': ['muscle', 'muddle', 'muzzle', 'mumble', 'muffle', 'muggle'],
                    'mace': ['malice'],
                    'male': ['mantle', 'marble', 'mangle'],
                    'nest': ['newest'],
                    'near': ['nectar'],
                    'neon': ['neuron', 'newton'],
                    'nine': ['nicene'],
                    'nile': ['nimble', 'nibble', 'nipple', 'nickle'],
                    'noon': ['notion'],
                    'oral': ['ordeal'],
                    'oxen': ['oxygen'],
                    'pale': ['paddle', 'parole'],
                    'pace': ['palace'],
                    'pole': ['poodle'],
                    'prey': ['pricey'],
                    'push': ['punish'],
                    'poet': ['pocket', 'poulet'],
                    'pity': ['pigsty'],
                    'pile': ['pickle', 'piddle', 'piffle', 'pimple'],
                    'pier': ['pilfer', 'pincer', 'picker'],
                    'pray': ['prepay'],
                    'peon': ['person'],
                    'pate': ['palate'],
                    'pant': ['patent', 'parent'],
                    'read': ['reread', 'reload', 'reclad'],
                    'room': ['romcom'],
                    'ring': ['rising', 'riding'],
                    'rule': ['rumble', 'ruffle', 'rubble', 'rustle'],
                    'reel': ['refuel'],
                    'real': ['reveal', 'repeal', 'rental'],
                    'rain': ['raisin'],
                    'rage': ['ravage'],
                    'role': ['royale'],
                    'rein': ['retain', 'remain', 'regain', 'rejoin'],
                    'rote': ['rotate'],
                    'rely': ['really'],
                    'reef': ['relief'],
                    'riff': ['ripoff'],
                    'rile': ['ripple', 'riddle'],
                    'rung': ['ruling'],
                    'suit': ['submit', 'summit', 'sunlit'],
                    'show': ['shadow'],
                    'spot': ['spigot'],
                    'spin': ['sprain'],
                    'sage': ['savage'],
                    'spit': ['spirit'],
                    'sure': ['suture'],
                    'send': ['second'],
                    'sale': ['sample', 'saddle'],
                    'shun': ['shogun'],
                    'scam': ['scream'],
                    'that': ['threat', 'throat'],
                    'this': ['thesis'],
                    'tide': ['tirade'],
                    'toil': ['tonsil'],
                    'tent': ['tenant', 'tenent'],
                    'tale': ['tackle', 'tangle', 'tattle', 'tamale', 'tassle'],
                    'tang': ['taking', 'taxing', 'taping', 'taming'],
                    'uses': ['usages'],
                    'vein': ['vermin'],
                    'vice': ['vivace'],
                    'vile': ['viable', 'virile'],
                    'vial': ['visual'],
                    'wary': ['watery'],
                    'wing': ['wiring', 'wining', 'wiling', 'wiping'],
                    'wily': ['widely', 'wildly', 'wisely', 'wiggly'],
                    'wiry': ['wintry', 'winery'],
                    'accent': ['accident'],
                    'banter': ['banister'],
                    'create': ['crewmate'],
                    'corral': ['corporal'],
                    'caring': ['carrying', 'caroling'],
                    'cheers': ['checkers', 'cheaters', 'cheerers'],
                    'cellar': ['cellular'],
                    'decent': ['decadent'],
                    'derive': ['derisive'],
                    'defend': ['defriend'],
                    'equity': ['equality'],
                    'estate': ['estimate'],
                    'edible': ['editable'],
                    'facile': ['facsmile'],
                    'garner': ['gardener'],
                    'homage': ['homepage'],
                    'innate': ['innovate'],
                    'intact': ['interact'],
                    'insure': ['insecure'],
                    'indent': ['indolent', 'indecent'],
                    'jumble': ['jumpable'],
                    'living': ['livening'],
                    'laying': ['layering'],
                    'metric': ['meteoric'],
                    'marble': ['markable'],
                    'notion': ['notation'],
                    'outing': ['outgoing', 'outlying', 'outdoing'],
                    'recess': ['reckless'],
                    'relate': ['relegate', 'relocate'],
                    'resent': ['resident'],
                    'spring': ['spraying', 'sprucing'],
                    'subtle': ['subtitle'],
                    'string': ['striking', 'striving', 'stroking', 'straying', 'strafing', 'striding', 'strobing'],
                    'stable': ['statable'],
                    'though': ['thorough'],
                    'toward': ['townward'],
                    'tenent': ['tenement'],
                    'unsung': ['unsprung', 'unstrung'],
                    'unsure': ['unsecure'],
                    'verity': ['veracity'],
                    'vanish': ['vanquish'],
                    'wading': ['waddling'],
                    'waters': ['watchers', 'waterers']
                }
